### ISSUE TITLE
Step 2 "TEST" -> เคสการแสดงหน่วยของช่อง Setting ของ Template Stopwatch

### ISSUE THREAD

**Issue by tomogikung** [tomogikung/GON-s-bug-deflector#18]
![Screen Shot 2019-02-21 at 10:21 AM](http://marker.screenshots.prod.s3.amazonaws.com/4f139a98e73c4321ab7ed8083f5f56cd-1550744497061.png)

**Summary:**
การแสดงหน่วยของช่อง Setting ของ Template Stopwatch เป็น องศา
**Steps to Reproduce:** 
เลือก Audit Unit เป็น "Stopwatch"
**Expected Results:** 
แสดง Header ค่า setting เป็น "Setting" 
**Actual Results:** 
แสดง Header ค่า setting เป็น "Setting (องศา)" 
**Notes:**
/

---
### More Info

**Reported by:** Athorn (tomogikung@gmail.com)
**Source URL**: [http://test.foodpassion.co.th/GON](http://test.foodpassion.co.th/GON)

<table><tr><td><strong>Browser</strong></td><td>Chrome 72.0.3626.109</td></tr><tr><td><strong>Screen Size</strong></td><td>1600 x 900</td></tr><tr><td><strong>OS</strong></td><td>Windows 8.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1616 x 876</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by jirawutFP** [comment]
แก้เเล้วครับ
