### ISSUE TITLE
Step 2 "TEST" -> เคสการแสดงผลทศนิยม

### ISSUE THREAD

**Issue by tomogikung** [tomogikung/GON-s-bug-deflector#19]
![Screen Shot 2019-02-21 at 10:35 AM](http://marker.screenshots.prod.s3.amazonaws.com/6351ec0553574ec8b11cfd22d89778de-1550745348208.png)

**Summary:**
การแสดงผลทศนิยมของ "ค่าเเก้ไข" เกินจำนวน 2 หลัก
**Steps to Reproduce:** 
กรอกข้อมูลใน Template Stopwatch ให้มีการคำนวนเป็นค่าทศนิยม
**Expected Results:** 
แสดงผลการคำนวนเป็นทศนิยมจำนวน 2 หลัก
**Actual Results:** 
แสดงผลการคำนวนเป็นทศนิยมมากกว่า2 หลัก
**Notes:**
รวมไปถึงการแสดงผลทศนิยมทั้งหมดในขั้นตอนที่ 2

---
### More Info

**Reported by:** Athorn (tomogikung@gmail.com)
**Source URL**: [http://test.foodpassion.co.th/GON](http://test.foodpassion.co.th/GON)

<table><tr><td><strong>Browser</strong></td><td>Chrome 72.0.3626.109</td></tr><tr><td><strong>Screen Size</strong></td><td>1600 x 900</td></tr><tr><td><strong>OS</strong></td><td>Windows 8.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1616 x 876</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by jirawutFP** [comment]
ทำเเล้วค่า
