### ISSUE TITLE
Step 2 "TEST" -> ไม่คำนวนค่าแก้ใข

### ISSUE THREAD

**Issue by tomogikung** [tomogikung/GON-s-bug-deflector#22]
![Screen Shot 2019-02-25 at 3:22 AM](http://marker.screenshots.prod.s3.amazonaws.com/3a14e6b3a36e4b6d95a65f2a61178b8f-1551064948172.png)

**Summary:**
ทดสอบการคำนวนค่าแก้ใข กรณีที่กดปุ่ม "Back" กลับมาแก้ไขผลการ test เดิม
**Steps to Reproduce:** 
แก้ไขข้อมูค่า Setting และค่า Master และ สาขาเพื่อให้เกิดการคำนวนใหม่
**Expected Results:** 
คำนวนผล "ค่าแก้ใข" ใหม่ตามการแก้ไขข้อมูล
**Actual Results:** 
ไม่มีการคำนวนผล "ค่าแก้ใข" ใหม่ตามการแก้ไขข้อมูล
**Notes:**
/

---
### More Info

**Reported by:** Athorn (tomogikung@gmail.com)
**Source URL**: [http://test.foodpassion.co.th/GON](http://test.foodpassion.co.th/GON)

<table><tr><td><strong>Browser</strong></td><td>Chrome 72.0.3626.109</td></tr><tr><td><strong>Screen Size</strong></td><td>1600 x 900</td></tr><tr><td><strong>OS</strong></td><td>Windows 8.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1616 x 876</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by jirawutFP** [comment]
ทำเเล้วค่า
